### ISSUE TITLE
TypeError: Cannot read property '10' of null

### ISSUE THREAD

**Issue by jpmolinamatute** [kuychaco/what-the-status#3]
I'm using Atom v1.27.1 and I get more 140 errors messages in the developer console

file with the problem `/usr/lib/atom/node_modules/what-the-status/index.js:190`

> Uncaught (in promise) TypeError: Cannot read property '10' of null
>     at parseUnmergedEntry (/usr/lib/atom/node_modules/what-the-status/index.js:190:20)
>     at parseLine (/usr/lib/atom/node_modules/what-the-status/index.js:73:7)
>     at Stream.<anonymous> (/usr/lib/atom/node_modules/what-the-status/index.js:36:31)
>     at emitOne (events.js:115:13)
>     at Stream.emit (events.js:210:7)
>     at drain (/usr/lib/atom/node_modules/through/index.js:36:16)
>     at Stream.stream.queue.stream.push (/usr/lib/atom/node_modules/through/index.js:45:5)
>     at emit (/usr/lib/atom/node_modules/split/index.js:37:14)
>     at next (/usr/lib/atom/node_modules/split/index.js:49:7)
>     at Stream.<anonymous> (/usr/lib/atom/node_modules/split/index.js:54:5)
>     at Stream.stream.write (/usr/lib/atom/node_modules/through/index.js:26:11)
>     at Readable.ondata (_stream_readable.js:628:20)
>     at emitOne (events.js:115:13)
>     at Readable.emit (events.js:210:7)
>     at Readable.read (_stream_readable.js:464:10)
>     at flow (_stream_readable.js:835:34)
>     at emitReadable_ (_stream_readable.js:503:3)
>     at _combinedTickCallback (internal/process/next_tick.js:135:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

if you need more information to debug/fix this issue, please let me know

**Comment by mikey-** [comment]
![image](https://user-images.githubusercontent.com/1870825/88524616-ec579780-d03c-11ea-8f0e-83fa83b8a156.png)

**Comment by Caellion** [comment]
sorry for necroing, but if you have possibility to still reproduce this, can you include result of running this command in that repo:
`git status --porcelain=v2 --branch --untracked-files=all --ignore-submodules=dirty -z`
because it seems that this regex https://github.com/kuychaco/what-the-status/blob/64688d745bc4324f08de8f0795cf5609d2cf6588/index.js#L8
doesn't match anything for some 140 unmerged files in your repo. I have encountered kind of similar bug, but in different circumstances and would like to at least write a test-case for the kind of git-output you got.

Things that come to mind:
* Renames with old filenames starting with `1`, `2`,`u` or `!`
* Some really obscure unicode characters in names
